org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC --enable-native-access=ALL-UNNAMED

org.gradle.configuration-cache=false
org.gradle.parallel=true

minecraft_version=26.2
loader_version=0.19.3

mod_version=5.0.0
maven_group=com.lavaboatclutch
archives_base_name=lava-boat-clutch-fix

fabric_version=0.152.1+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.0-beta.1
