plugins {
    id 'net.neoforged.moddev' version '2.0.141'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        lava_boat_clutch {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

test {
    enabled = false
}
